Sprint 4
anton-kashnikoff/MovieQuiz-ios pull request #2
Opened 2023-03-08 20:04 UTC by prostokot14

2023-03-09 14:54 UTC, protos17 requested changes

2023-03-09 14:54 UTC, protos17 commented on MovieQuiz/AppDelegate.swift
>          // Override point for customization after application launch.
Рекомендую удалять лишний закомментированный код

2023-03-09 14:54 UTC, protos17 commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var ypWhite: UIColor { UIColor(named: "ypWhite") ?? UIColor.white }
Название цветов, указанных здесь, отличается от тех,  что указаны в Assets.Colors

2023-03-09 14:54 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        QuizQuestion(image: "The Godfather", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
Повторяющуюся строку рекомендую вынести в отдельную константу

2023-03-09 14:54 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true // даём разрешение на рисование рамки
Здесь необходимо добавить layer.cornerRadius

2023-03-09 14:54 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Было бы неплохо здесь блокировать кнопки

2023-03-09 14:54 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.showNextQuestionOrResults()
а здесь эти кнопки разблокировать

2023-03-14 13:06 UTC, prostokot14 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        QuizQuestion(image: "The Godfather", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
Пытаюсь добавить вопрос в константу, но появляется ошибка: "Cannot use instance member 'question' within property initializer; property initializers run before 'self' is available"

2023-03-14 15:17 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        QuizQuestion(image: "The Godfather", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: true),
Можео сделать его static или вычисляемым свойством

2023-03-15 13:05 UTC, protos17 approved these changes

2023-03-15 13:05 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet var yesButton: UIButton!
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-15 13:05 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet var noButton: UIButton!
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-15 13:53 UTC, prostokot14 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true // даём разрешение на рисование рамки
Почему-то если я добавляю это здесь, то при первом открытии экрана углы не закругляются. А если добавляю здесь и в методе show(quiz result:), то рамка на первом вопросе становится цветной "вовнутрь" картинки, а на остальных "наружу". Не понимаю, как это работает

2023-03-15 13:54 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true // даём разрешение на рисование рамки
Чтобы при первом открытии отображалось, нужно в сториборде это добавить

2023-03-15 15:16 UTC, prostokot14 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true // даём разрешение на рисование рамки
Спасибо!

2023-03-15 15:27 UTC, merged