Sprint 05
anton-kashnikoff/MovieQuiz-ios pull request #3
Opened 2023-03-29 13:53 UTC by prostokot14

2023-03-29 15:22 UTC, protos17 requested changes

2023-03-29 15:22 UTC, protos17 commented on MovieQuiz/Models/QuizQuestion.swift
> +    let text: String
Вопрос у тебя всегда один и тот же, лучше его написать сразу здесь как значение по умолчанию

2023-03-29 15:22 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +class AlertPresenter: AlertPresenterProtocol {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием.

2023-03-29 15:22 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +        }
Рекомендую здесь реализовать проверку, что этот вопрос не был показан ранее

2023-03-29 15:22 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +        let currentBestGame = GameRecord(correct: correct, total: total, date: Date())
Для корректной работы здесь вместо correct надо передавать count, вместо total - amount

2023-03-29 16:01 UTC, prostokot14 commented on MovieQuiz/Services/QuestionFactory.swift
> +        }
Не получается придумать, как это реализовать( Думал об удалении элементов (фильмов) из массива, но потом их нужно будет где-то добавлять обратно.. Думал, чтобы сохранять индексы, тоже получается болото какое-то(

2023-03-29 17:48 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +        }
Ну это необязательное задание, можешь оставить так

2023-03-31 06:18 UTC, merged

2023-04-01 05:58 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +        QuizQuestion(image: "Vivarium", text: "Рейтинг этого фильма больше чем 6?", correctAnswer: false)
У тебя вопрос дублируется 10 раз, рекомендую избегать дублирование